### PR TITLE
Fix accessing the object as array

### LINKED ISSUE #452: Error when exporting MongoDb data with DoctrineODMQuerySourceIterator
#### Sonata packages

<details><summary>show</summary>
<p>

```
$ composer show --latest 'sonata-project/*'  
sonata-project/admin-bundle                  3.88.0 3.89.1 The missing Symfony Admin Generator
sonata-project/block-bundle                  4.5.0  4.5.0  Symfony SonataBlockBundle
sonata-project/cache                         2.0.1  2.1.1  Cache library
sonata-project/doctrine-extensions           1.11.0 1.11.0 Doctrine2 behavioral extensions
sonata-project/doctrine-mongodb-admin-bundle 3.7.0  3.7.0  Symfony Sonata / Integrate Doctrine MongoDB ODM into the SonataAdminBundle
sonata-project/doctrine-orm-admin-bundle     3.29.0 3.29.0 Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/exporter                      2.5.1  2.5.1  Lightweight Exporter library
sonata-project/form-extensions               1.9.0  1.9.0  Symfony form extensions
sonata-project/twig-extensions               1.5.1  1.5.1  Sonata twig extensions
```

</p>
</details>

#### Symfony packages

<details><summary>show</summary>
<p>

```
$ composer show --latest 'symfony/*'
symfony/asset                      v4.4.8  v5.2.3  Symfony Asset Component
symfony/browser-kit                v4.4.8  v5.2.3  Symfony BrowserKit Component
symfony/cache                      v4.4.8  v5.2.3  Symfony Cache component with PSR-6, PSR-16, and tags
symfony/cache-contracts            v2.0.1  v2.2.0  Generic abstractions related to caching
symfony/config                     v4.4.17 v5.2.3  Symfony Config Component
symfony/console                    v4.4.8  v5.2.3  Symfony Console Component
symfony/css-selector               v4.4.8  v5.2.3  Symfony CssSelector Component
symfony/debug                      v4.4.8  v4.4.19 Symfony Debug Component
symfony/debug-bundle               v4.4.8  v5.2.3  Symfony DebugBundle
symfony/debug-pack                 v1.0.8  v1.0.9  A debug pack for Symfony projects
symfony/dependency-injection       v4.4.17 v5.2.3  Symfony DependencyInjection Component
symfony/deprecation-contracts      v2.2.0  v2.2.0  A generic function and convention to trigger deprecation notices
symfony/doctrine-bridge            v4.4.8  v5.2.3  Symfony Doctrine Bridge
symfony/dom-crawler                v4.4.8  v5.2.3  Symfony DomCrawler Component
symfony/dotenv                     v4.4.8  v5.2.3  Registers environment variables from a .env file
symfony/error-handler              v4.4.8  v5.2.3  Symfony ErrorHandler Component
symfony/event-dispatcher           v4.4.8  v5.2.3  Symfony EventDispatcher Component
symfony/event-dispatcher-contracts v1.1.7  v2.2.0  Generic abstractions related to dispatching event
symfony/expression-language        v4.4.8  v5.2.3  Symfony ExpressionLanguage Component
symfony/filesystem                 v4.4.17 v5.2.3  Symfony Filesystem Component
symfony/finder                     v4.4.8  v5.2.3  Symfony Finder Component
symfony/flex                       v1.9.5  v1.12.2 Composer plugin for Symfony
symfony/form                       v4.4.19 v5.2.3  Allows to easily create, process and reuse HTML forms
symfony/framework-bundle           v4.4.8  v5.2.3  Symfony FrameworkBundle
symfony/http-client                v4.4.8  v5.2.3  Symfony HttpClient component
symfony/http-client-contracts      v2.0.1  v2.3.1  Generic abstractions related to HTTP clients
symfony/http-foundation            v4.4.8  v5.2.3  Symfony HttpFoundation Component
symfony/http-kernel                v4.4.13 v5.2.3  Symfony HttpKernel Component
symfony/inflector                  v4.4.8  v5.2.3  Symfony Inflector Component
symfony/intl                       v4.4.8  v5.2.3  A PHP replacement layer for the C intl extension that includes additional data from the ICU library.
symfony/lock                       v4.4.8  v5.2.3  Symfony Lock Component
symfony/mailer                     v4.4.8  v5.2.3  Symfony Mailer Component
symfony/maker-bundle               v1.15.1 v1.29.1 Symfony Maker helps you create empty commands, controllers, form classes, tests and more so you can forge...
symfony/messenger                  v4.4.8  v5.2.3  Symfony Messenger Component
symfony/mime                       v4.4.13 v5.2.3  A library to manipulate MIME messages
symfony/monolog-bridge             v4.4.8  v5.2.3  Symfony Monolog Bridge
symfony/monolog-bundle             v3.5.0  v3.6.0  Symfony MonologBundle
symfony/options-resolver           v4.4.11 v5.2.3  Symfony OptionsResolver Component
symfony/orm-pack                   v1.0.8  v2.1.0  A pack for the Doctrine ORM
symfony/polyfill-ctype             v1.20.0 v1.22.1 Symfony polyfill for ctype functions
symfony/polyfill-intl-grapheme     v1.15.0 v1.22.1 Symfony polyfill for intl's grapheme_* functions
symfony/polyfill-intl-icu          v1.15.0 v1.22.1 Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-intl-idn          v1.15.0 v1.22.1 Symfony polyfill for intl's idn_to_ascii and idn_to_utf8 functions
symfony/polyfill-intl-normalizer   v1.15.0 v1.22.1 Symfony polyfill for intl's Normalizer class and related functions
symfony/polyfill-mbstring          v1.15.0 v1.22.1 Symfony polyfill for the Mbstring extension
symfony/polyfill-php72             v1.15.0 v1.22.1 Symfony polyfill backporting some PHP 7.2+ features to lower PHP versions
symfony/polyfill-php73             v1.15.0 v1.22.1 Symfony polyfill backporting some PHP 7.3+ features to lower PHP versions
symfony/polyfill-php80             v1.18.1 v1.22.1 Symfony polyfill backporting some PHP 8.0+ features to lower PHP versions
symfony/process                    v4.4.8  v5.2.3  Symfony Process Component
symfony/profiler-pack              v1.0.4  v1.0.5  A pack for the Symfony web profiler
symfony/property-access            v4.4.8  v5.2.3  Symfony PropertyAccess Component
symfony/property-info              v4.4.11 v5.2.3  Symfony Property Info Component
symfony/psr-http-message-bridge    v1.3.0  v2.1.0  PSR HTTP message bridge
symfony/routing                    v4.4.8  v5.2.3  Symfony Routing Component
symfony/security-acl               v3.1.1  v3.1.1  Symfony Security Component - ACL (Access Control List)
symfony/security-bundle            v4.4.8  v5.2.3  Symfony SecurityBundle
symfony/security-core              v4.4.8  v5.2.3  Symfony Security Component - Core Library
symfony/security-csrf              v4.4.8  v5.2.3  Symfony Security Component - CSRF Library
symfony/security-guard             v4.4.8  v5.2.3  Symfony Security Component - Guard
symfony/security-http              v4.4.8  v5.2.3  Symfony Security Component - HTTP Integration
symfony/serializer                 v4.4.11 v5.2.3  Symfony Serializer Component
symfony/serializer-pack            v1.0.3  v1.0.4  A pack for the Symfony serializer
symfony/service-contracts          v2.2.0  v2.2.0  Generic abstractions related to writing services
symfony/stopwatch                  v4.4.8  v5.2.3  Symfony Stopwatch Component
symfony/string                     v5.2.3  v5.2.3  Provides an object-oriented API to strings and deals with bytes, UTF-8 code points and grapheme clusters ...
symfony/templating                 v4.4.8  v5.2.3  Symfony Templating Component
symfony/translation                v4.4.8  v5.2.3  Symfony Translation Component
symfony/translation-contracts      v2.0.1  v2.3.0  Generic abstractions related to translation
symfony/twig-bridge                v4.4.8  v5.2.3  Symfony Twig Bridge
symfony/twig-bundle                v4.4.8  v5.2.3  Symfony TwigBundle
symfony/twig-pack                  v1.0.0  v1.0.1  A Twig pack for Symfony projects
symfony/validator                  v4.4.8  v5.2.3  Symfony Validator Component
symfony/var-dumper                 v4.4.8  v5.2.3  Symfony mechanism for exploring and dumping PHP variables
symfony/var-exporter               v4.4.8  v5.2.3  A blend of var_export() + serialize() to turn any serializable data structure to plain PHP code
symfony/web-profiler-bundle        v4.4.8  v5.2.3  Symfony WebProfilerBundle
symfony/webpack-encore-bundle      v1.7.3  v1.11.1 Integration with your Symfony app & Webpack Encore!
symfony/workflow                   v4.4.8  v5.2.3  Symfony Workflow Component
symfony/yaml                       v4.4.8  v5.2.3  Symfony Yaml Component
```

</p>
</details>

#### PHP version

```
$ php -v
PHP 7.4.13 (cli) (built: Nov 30 2020 20:40:09) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.13, Copyright (c), by Zend Technologies
```

## Subject

When exporting data from mongodb in Sonata Admin, the file got is filled by Symfony error. The DoctrineODMQuerySourceIterator got an object instead of an array.

## Steps to reproduce
In Sonata Admin, go to a list of mongodb records. Export the list (whatever the format).
## Expected results
Data are exported in desired format.
## Actual results
The file is available, but with a Symfony error in it.

```
Error:
Cannot use object of type App\Document\MyObject as array

  at /vendor/sonata-project/exporter/src/Source/DoctrineODMQuerySourceIterator.php:39
  at Sonata\Exporter\Source\DoctrineODMQuerySourceIterator->current()
     (//vendor/sonata-project/exporter/src/Handler.php:41)
  at Sonata\Exporter\Handler->export()
     (/vendor/sonata-project/exporter/src/Exporter.php:58)
  at Sonata\Exporter\Exporter::Sonata\Exporter\{closure}()
     (/vendor/symfony/http-foundation/StreamedResponse.php:112)
  at Symfony\Component\HttpFoundation\StreamedResponse->sendContent()
     (/vendor/symfony/http-foundation/Response.php:381)
  at Symfony\Component\HttpFoundation\Response->send()
     (/vendor/symfony/http-kernel/EventListener/StreamedResponseListener.php:41)
  at Symfony\Component\HttpKernel\EventListener\StreamedResponseListener->onKernelResponse()
     (/vendor/symfony/event-dispatcher/Debug/WrappedListener.php:126)
  at Symfony\Component\EventDispatcher\Debug\WrappedListener->__invoke()
     (/vendor/symfony/event-dispatcher/EventDispatcher.php:264)
  at Symfony\Component\EventDispatcher\EventDispatcher->doDispatch()
     (/vendor/symfony/event-dispatcher/EventDispatcher.php:239)
  at Symfony\Component\EventDispatcher\EventDispatcher->callListeners()
     (/vendor/symfony/event-dispatcher/EventDispatcher.php:73)
  at Symfony\Component\EventDispatcher\EventDispatcher->dispatch()
     (/vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php:168)
  at Symfony\Component\EventDispatcher\Debug\TraceableEventDispatcher->dispatch()
     (/vendor/symfony/http-kernel/HttpKernel.php:191)
  at Symfony\Component\HttpKernel\HttpKernel->filterResponse()
     (/vendor/symfony/http-kernel/HttpKernel.php:179)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw()
     (/vendor/symfony/http-kernel/HttpKernel.php:80)
  at Symfony\Component\HttpKernel\HttpKernel->handle()
     (/vendor/symfony/http-kernel/Kernel.php:201)
  at Symfony\Component\HttpKernel\Kernel->handle()
     (/public/index.php:25)        
```

### PR DESCRIPTION
**Pull request by franmomu**
## Subject

When using MongoDB, IterableResult::current() method returns the current document, not an array.

I am targeting this branch, because this is a bugfix.

Closes #452.

## Changelog

```markdown
### Fixed
- Fixed iterating over documents when using `DoctrineODMQuerySourceIterator`.
```

Can you please try it @webdevilopers?

### CODE REVIEW

File: tests/Source/DoctrineODMQuerySourceIteratorTest.php [hunk 1]
```diff
@@ -0,0 +1,81 @@
...
+            ->execute();
+    }
+
+    public function testHandler(): void
+    {
+        $query = $this->dm->createQueryBuilder(Document::class)->getQuery();
+
+        $iterator = new DoctrineODMQuerySourceIterator($query, ['id']);
+
+        $results = [];
```
Comment (phansys) [inline tests/Source/DoctrineODMQuerySourceIteratorTest.php:57]: Why not [`iterator_to_array()`](https://www.php.net/manual/en/function.iterator-to-array.php)?

Comment (franmomu) [reply tests/Source/DoctrineODMQuerySourceIteratorTest.php]: Because laziness, I had copied it from https://github.com/sonata-project/exporter/blob/2.x/tests/Source/PDOStatementSourceIteratorTest.php#L68 and didn't look too much 😬, changed.

**Review by VincentLanglet — APPROVED** [review]

**Review by jordisala1991 — APPROVED** [review]

**Review by phansys — APPROVED** [review]

**Comment by phansys** [comment]
Thank you @franmomu!

**Comment by webdevilopers** [comment]
Wow, that was fast. I couldn't even test it in time. :)
If understand correctly I will have to use the `sonata-project:2.x` branch to test it, NOT the `master`?
Or will it be merged into `master` next?

Once again: thanks!

**Comment by webdevilopers** [comment]
I tried `"sonata-project/exporter": "2.x"`.

Which will install **2.5.1**.

The confusing part is the symfony recipe that adds the following line to `bundles.php`:

```php
Sonata\Exporter\Bridge\Symfony\SonataExporterSymfonyBundle::class => ['all' => true],
```

Which should be:

```php
Sonata\Exporter\Bridge\Symfony\SonataExporterBundle::class => ['all' => true],
```

?

**Comment by franmomu** [comment]
It's already merged in `master` :)

About the `bundles.php`, the problem is that there is no recipe for this (I don't remember right now, but I think they don't accept a recipe to just specify the bundle path) and we had to [create this `SonataExporterSymfonyBundle` so Symfony flex adds that file path automatically.](https://github.com/sonata-project/exporter/pull/345), ideally this package should split into library and bundle.

**Comment by webdevilopers** [comment]
Okay, I now use these packages:

```javascript
        "friendsofsymfony/user-bundle": "dev-master",
        "sonata-project/admin-bundle": "^3.93",
        "sonata-project/doctrine-mongodb-admin-bundle": "^3.7",
        "sonata-project/exporter": "2.5.1",
        "sonata-project/intl-bundle": "^2.10.1",
```

The URL for export:

http://dev.example.com/admin/app/businessprofile/export?filter%5B_sort_order%5D=ASC&filter%5B_sort_by%5D=id&filter%5B_page%5D=0&filter%5B_per_page%5D=32&format=csv

I still get **Cannot use object of type App\Document\BusinessProfile as array**.

Am I missing something?

```php
<?php declare(strict_types=1);

namespace App\Document;

use Doctrine\ODM\MongoDB\Mapping\Annotations as MongoDB;

/**
 * @MongoDB\Document(collection="business_profile_details", readOnly=true)
 */
class BusinessProfile
{
    /**
     * @MongoDB\Id()
     * @internal
     */
    protected $id;

    /**
     * @MongoDB\Field(type="string")
     */
    protected $businessProfileId;

    /**
     * @MongoDB\Field(type="string")
     */
    protected $accountId;

    /**
     * @MongoDB\EmbedOne(targetDocument=ContactInformation::class)
     */
    protected $contactInformation;

    /**
     * @MongoDB\EmbedOne(targetDocument=ContactPerson::class)
     */
    protected ContactPerson $contactPerson;

    /**
     * @MongoDB\EmbedOne(targetDocument=BillingInformation::class)
     */
    protected BillingInformation $billingInformation;

    /**
     * @MongoDB\Field(type="bool")
     */
    protected $activePlan;

    /**
     * @MongoDB\Field(type="string")
     */
    protected $plan;

    /**
     * @MongoDB\Field(type="date", name="projectedAt")
     */
    protected $createdAt;

    public function businessProfileId()
    {
        return $this->businessProfileId;
    }

    public function account()
    {
        return $this->account;
    }

    public function accountId()
    {
        return $this->accountId;
    }

    public function contactInformation(): ContactInformation
    {
        return $this->contactInformation;
    }

    public function contactPerson(): ContactPerson
    {
        return $this->contactPerson;
    }

    public function billingInformation(): BillingInformation
    {
        return $this->billingInformation;
    }

    public function activePlan()
    {
        return $this->activePlan;
    }

    public function plan()
    {
        return $this->plan;
    }

    public function createdAt()
    {
        return $this->createdAt;
    }
}

```

**Comment by webdevilopers** [comment]
I also tried adding `dev-master` but this will currently conflict:

```
  Problem 1
    - sonata-project/admin-bundle 3.93.0 requires sonata-project/exporter ^1.11 || ^2.0 -> satisfiable by sonata-project/exporter[1.x-dev, 2.x-dev].
    - sonata-project/admin-bundle 3.93.0 requires sonata-project/exporter ^1.11 || ^2.0 -> satisfiable by sonata-project/exporter[1.x-dev, 2.x-dev].
    - sonata-project/admin-bundle 3.x-dev requires sonata-project/exporter ^1.11 || ^2.0 -> satisfiable by sonata-project/exporter[1.x-dev, 2.x-dev].
    - Can only install one of: sonata-project/exporter[dev-master, 1.x-dev].
    - Can only install one of: sonata-project/exporter[dev-master, 2.x-dev].
    - Installation request for sonata-project/exporter dev-master -> satisfiable by sonata-project/exporter[dev-master].
    - Installation request for sonata-project/admin-bundle ^3.93 -> satisfiable by sonata-project/admin-bundle[3.93.0, 3.x-dev].
```

**Comment by webdevilopers** [comment]
Got it, will have to use ```"sonata-project/exporter": "2.x-dev",```. Testing...

**Comment by webdevilopers** [comment]
That seems to work! But it looks like that the Exporter always requires the Identifier.

**Neither the property "id" nor one of the methods "getId()", "id()", "isId()", "hasId()", "__get()" exist and have public access in class "App\Document\BusinessProfile".**

```php

**Comment by VincentLanglet** [comment]
By default, SonataAdmin just try to export every field if you don't override `getExportField()`

**Comment by webdevilopers** [comment]
Exactly, this would fix it:

```php
    protected function configureExportFields(): array
    {
        return ['businessProfileId'];
    }
```

Thanks for you help!
