### PR TITLE
[Bug] Actually use the escape parameter.

### LINKED ISSUE #219: [Bug] Actually use the escape parameter.
## Subject
The construct method takes an escape character string, but never actually uses it when running fputcsv. 

## Steps to reproduce
Try using CsvWriter with a custom escape character.

## Expected results
You'd expect that character to be used, since it's taken as a param.

## Actual results
It uses the default escape character always.

### PR DESCRIPTION
**Pull request by heathdutton**
I am targeting this branch, because this is not BC breaking, just a breakfix.

Closes #219 

### Fixed
- CsvWriter actually uses the escape parameter.

## Subject

Simplified version of the PR to just fix the missing params.

### CODE REVIEW

**Comment by heathdutton** [comment]
Looks like the tests need fixing, on it.

**Comment by greg0ire** [comment]
> just a breakfix.

I hope this is not what it sounds like :sweat_smile:

File: tests/Writer/CsvWriterTest.php [hunk 1]
```diff
@@ -59,9 +59,24 @@ public function testEnclosureFormating()
         $this->assertEquals($expected, trim(file_get_contents($this->filename)));
     }
 
+    public function testEscapeFormating()
+    {
+        $writer = new CsvWriter($this->filename, ',', '"', '/', false);
+
+        $writer->open();
+
+        $writer->write(['john','doe', '\\', '/']);
```
Comment (greg0ire) [inline tests/Writer/CsvWriterTest.php]: flintci is complaining about the missing space before `'doe'`

**Comment by greg0ire** [comment]
Thanks @heathdutton for fixing that embarrassing mistake :sweat_smile:

**Comment by heathdutton** [comment]
Thanks for not laughing at my PRs :)

**Comment by kunicmarko20** [comment]
@heathdutton thank you for finding and fixing this bug!
